# Generated by Django 4.2.14 on 2024-08-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contactview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFLightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TravelClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flying_from', models.CharField(max_length=128)),
                ('flying_to', models.CharField(max_length=128)),
                ('departing', models.DateTimeField()),
                ('returning', models.DateTimeField()),
                ('number_of_adults', models.PositiveIntegerField(default=0)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.categoryflightmodel')),
                ('travelClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.travelclassmodel')),
            ],
            options={
                'verbose_name': 'Flights',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
