# Generated by Django 4.2.14 on 2024-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_categoryflightmodel_travelclassmodel_flightmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='departing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='returning',
            field=models.DateField(),
        ),
    ]
