# Generated by Django 4.2.14 on 2024-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_travelclassmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclassmodel',
            name='name',
            field=models.CharField(default='Economy', max_length=128),
        ),
    ]
